### PR TITLE
Add raw mode special case SI modes

### PR DESCRIPTION
**Pull request by jeanconn**
Add raw mode special case SI modes

This is a fix for #23

### CODE REVIEW

**Comment by jeanconn** [comment]
This is a little tricky to test as I can't fetch that actual SI mode from telemetered products to verify.  I can, however, verify raw mode from a telemetered ACIS parameter block, so I could re-run cmd_states for a big chunk of time and verify that the very tiny set of changed observations are all raw mode.

**Comment by taldcroft** [comment]
@jeanconn @jzuhone - I'm guessing that since this PR hasn't had any action in 3 years that it is not necessary?  Kadi command states is the way forward in any case.

**Comment by taldcroft** [comment]
Overtaken by kadi dynamic command states.

**Comment by jeanconn** [comment]
I'm not sure if "overtaken" is fair (because I don't think these SI mode fixes are in kadi dynamic command states either), but agree that there didn't seem to be a fire under this one.

**Pull request closed without merging**
