### PR TITLE
Add dither amplitude and period to cmd_states

### PR DESCRIPTION
**Pull request by jeanconn**
Add dither amplitude and period to cmd_states

### CODE REVIEW

**Comment by jeanconn** [comment]
I need dither parameters for higher-fidelity checking in starcheck (I don't want to "penalize" observations with 20 arcsec dither).  Since we don't get dither parameters from HISTORY files and we don't have a some kind of new continuity file standard set up in products yet, I thought this might be a quick way to go.  We are already using command states for values for the thermal models within starcheck so there is some support for using content from the database to review flight products.

I considered using timelines to just fetch and read dither from previous backstop files, but I couldn't immediately decide if that method would be as robust as just adding the columns I wanted to cmd_states.

**Comment by taldcroft** [comment]
OK looks good.  Just double check that the conversion from cmd parameters to our units is correct.

**Comment by jeanconn** [comment]
Do we need buy in from anybody else?  As I understand it, this will change the default returned columns from get_cmd_states, which should be fine unless somebody is doing their own text parsing of that and *also* using the default list of columns.

**Comment by taldcroft** [comment]
Yes we need to put this through the LR change process.

**Comment by taldcroft** [comment]
And of course there will be many changes to the actual states.

**Comment by jeanconn** [comment]
And yes, I assumed LR, but I didn't know about just drawing ACIS attention to this PR.

**Comment by taldcroft** [comment]
Yup.  Probably an email and include Matt as well.

**Comment by jeanconn** [comment]
Given our move to use of dynamic command states, I think this can just be closed unmerged.

**Comment by taldcroft** [comment]
:tada: :rocket:

**Pull request closed without merging**
