### PR TITLE
Remove OCC mode and HEAD FTP pushes

### PR DESCRIPTION
**Pull request by jeanconn**
Remove OCC mode and HEAD FTP pushes

### CODE REVIEW

**Comment by taldcroft** [comment]
Thanks, looks good.  At this point you might as well just remove the `--occ` command line option so it doesn't even show up in help.

**Comment by jeanconn** [comment]
OK, I suppose we are the only users and are unlikely to be surprised.

**Comment by jeanconn** [comment]
Also, I think we've got no useful tests in here.

**Comment by taldcroft** [comment]
For testing you can use the NetApp snapshot to get the oldest available version of the cmd_states.db3 and h5, copy those to local dir and then run the update script. That should run successfully and show states being added.
```
aca-kadi% ls -l /proj/sot/.snapshot/weekly.2019-07-28_0015/ska/data/cmd_states/cmd_states.*
-rw-r--r-- 1 aca aspect 222273536 Jul 24 15:33 /proj/sot/.snapshot/weekly.2019-07-28_0015/ska/data/cmd_states/cmd_states.db3
-rw-r--r-- 1 aca aspect  19995322 Jul 24 16:33 /proj/sot/.snapshot/weekly.2019-07-28_0015/ska/data/cmd_states/cmd_states.h5
aca-kadi% ls -l /proj/sot/ska/data/cmd_states/cmd_states.*
-rw-r--r-- 1 aca aspect 222479360 Aug  1 14:26 /proj/sot/ska/data/cmd_states/cmd_states.db3
-rw-r--r-- 1 aca aspect  20016230 Aug  1 14:25 /proj/sot/ska/data/cmd_states/cmd_states.h5
```

**Comment by jeanconn** [comment]
One can't run the update script in isolation, but I did run it with the other timelines code and see the expected result.  I left the output on verbose so:

```
ska-fido: ./update_cmd_states.py --dbi 'sqlite' --server cmd_states.db3 --h5file cmd_states.h5 --loglevel 10
Running update_cmd_states.py at Tue Aug  6 10:44:11 2019
Connecting to db: dbi=sqlite server=cmd_states.db3 user=None database=None
Getting initial state0
get_state0: found definitive state at 2019:208:13:05:30.816
Initial state0: datestart=2019:208:13:05:30.816 datestop=2019:208:13:10:35.085 obsid=21228
Getting timeline_loads after 2019:208:13:05:30.816
Found 24 timeline_loads
Getting cmds after 2019:208:13:05:30.816
get_cmds: got  36 cmds from db for timeline_id=426103855 (2019:207:17:50:00.966 - 2019:209:00:06:28.070)
get_cmds: got  68 cmds from db for timeline_id=426103856 (2019:207:17:50:00.966 - 2019:209:00:06:28.070)
get_cmds: got  60 cmds from db for timeline_id=426103857 (2019:209:02:55:02.958 - 2019:210:01:19:43.009)
get_cmds: got 139 cmds from db for timeline_id=426103858 (2019:209:02:55:02.958 - 2019:210:01:19:43.009)
get_cmds: got  20 cmds from db for timeline_id=426103859 (2019:210:01:16:43.009 - 2019:211:10:53:04.370)
get_cmds: got  66 cmds from db for timeline_id=426103860 (2019:210:01:16:43.009 - 2019:211:10:53:04.370)
get_cmds: got  24 cmds from db for timeline_id=426103861 (2019:211:11:11:51.107 - 2019:212:20:45:02.313)
get_cmds: got  52 cmds from db for timeline_id=426103862 (2019:211:11:11:51.107 - 2019:212:20:45:02.313)
get_cmds: got  12 cmds from db for timeline_id=426103863 (2019:213:00:18:47.948 - 2019:214:08:49:59.000)
get_cmds: got  40 cmds from db for timeline_id=426103864 (2019:213:00:18:47.948 - 2019:214:08:49:59.000)
get_cmds: got  20 cmds from db for timeline_id=426103865 (2019:214:09:31:55.238 - 2019:215:18:30:01.285)
get_cmds: got  69 cmds from db for timeline_id=426103866 (2019:214:09:31:55.238 - 2019:215:18:30:01.285)
get_cmds: got  16 cmds from db for timeline_id=426103867 (2019:215:20:00:01.285 - 2019:216:18:00:59.000)
get_cmds: got  51 cmds from db for timeline_id=426103868 (2019:215:20:00:01.285 - 2019:216:18:00:59.000)
get_cmds: got   0 cmds from db for timeline_id=426103869 (2019:216:18:01:00.001 - 2019:218:03:29:18.718)
get_cmds: got 20 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 20 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103870 (2019:216:18:01:00.001 - 2019:218:03:29:18.718)
get_cmds: got 52 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 52 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103871 (2019:218:04:45:01.285 - 2019:219:13:55:44.351)
get_cmds: got 20 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 20 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103872 (2019:218:04:45:01.285 - 2019:219:13:55:44.351)
get_cmds: got 38 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 38 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103873 (2019:219:14:48:30.146 - 2019:220:19:30:02.313)
get_cmds: got 16 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 16 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103874 (2019:219:14:48:30.146 - 2019:220:19:30:02.313)
get_cmds: got 40 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 40 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103875 (2019:221:02:46:02.040 - 2019:222:12:35:01.285)
get_cmds: got 24 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 24 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103876 (2019:221:02:46:02.040 - 2019:222:12:35:01.285)
get_cmds: got 62 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 62 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103877 (2019:222:14:05:01.285 - 2019:223:12:21:08.585)
get_cmds: got 8 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 8 cmds to commands tables
get_cmds: got   0 cmds from db for timeline_id=426103878 (2019:222:14:05:01.285 - 2019:223:12:21:08.585)
get_cmds: got 32 commands from /data/mpcrit1/mplogs/2019/AUG0519/oflsa/CR216_1805.backstop
insert_cmds_db: inserting 32 cmds to commands tables
Found 946 cmds after 2019:208:13:05:30.816
Generating cmd_states after 2019:208:13:05:30.816
get_states: starting from 2019:208:13:05:30.816
Maneuver at 2019:208:13:10:45.336 680620314.52

...

update_states_db: removed HDF5 cmd_states rows from 365783 to 365783
update_states_db: DELETE FROM cmd_states WHERE datestart >= '2019:216:17:58:57.926'
update_states_db: inserting states[674:1056] to HDF5 cmd_states
update_states_db: inserting states[674:1056] to database cmd_states
```

**Comment by taldcroft** [comment]
Looks good, but can you clarify "One can't run the update script in isolation, but I did run it with the other timelines code."

**Comment by jeanconn** [comment]
Sure, if you really want it :smile: .  One can't just copy the old files and and run "update_cmd_states.py", as it works relative to the timelines and load segments within cmd_states.db3 (so it will just say "nothing to update").
I ran 
```
cp /proj/sot/.snapshot/weekly.2019-07-28_0015/ska/data/cmd_states/cmd_states.db3 .
cp /proj/sot/.snapshot/weekly.2019-07-28_0015/ska/data/cmd_states/cmd_states.h5 .
```
and then
```
ska-fido: /proj/sot/ska/share/timelines/parse_cmd_load_gen.pl --dbi 'sqlite' --server cmd_states.db3 --verbose --touch_file notouch
```
I was too lazy to make a "touch file" with the right date, so this re-parsed all of those load generation summaries from the beginning of the mission while I did other things.  Then:

```ska-fido: /proj/sot/ska/share/timelines/update_load_seg_db.py  --dbi 'sqlite' --server cmd_states.db3 --verbose 
Connecting to sqlite server cmd_states.db3
LOAD_SEG DEBUG: Updating from /proj/sot/ska/data/arc/iFOT_events/load_segment/2019:218:14:41:01.000.rdb
LOAD_SEG INFO: Updating Loads for range 2019:198:11:10:00.000 to 2019:223:12:21:08.585
LOAD_SEG DEBUG: inserting load
	 CL216:1805 2019 2019:216:18:01:00.001 2019:218:03:29:18.718 128
LOAD_SEG DEBUG: inserting load
	 CL216:1805 2019 2019:216:18:01:00.001 2019:218:03:29:18.718 131
LOAD_SEG DEBUG: inserting load
	 CL218:0405 2019 2019:218:04:45:01.285 2019:219:13:55:44.351 129
LOAD_SEG DEBUG: inserting load
	 CL218:0405 2019 2019:218:04:45:01.285 2019:219:13:55:44.351 132
LOAD_SEG DEBUG: inserting load
	 CL219:1405 2019 2019:219:14:48:30.146 2019:220:19:30:02.313 130
LOAD_SEG DEBUG: inserting load
	 CL219:1405 2019 2019:219:14:48:30.146 2019:220:19:30:02.313 133
LOAD_SEG DEBUG: inserting load
	 CL221:0205 2019 2019:221:02:46:02.040 2019:222:12:35:01.285 128
LOAD_SEG DEBUG: inserting load
	 CL221:0205 2019 2019:221:02:46:02.040 2019:222:12:35:01.285 131
LOAD_SEG DEBUG: inserting load
	 CL222:1405 2019 2019:222:14:05:01.285 2019:223:12:21:08.585 129
LOAD_SEG DEBUG: inserting load
	 CL222:1405 2019 2019:222:14:05:01.285 2019:223:12:21:08.585 132
TIMELINES INFO: Updating timelines for range 2019:198:11:10:00.000 to 2019:223:12:21:08.585
TIMELINES INFO: inserting timelines[28:39] to timelines
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:216:18:01:00.001 2019:218:03:29:18.718
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:216:18:01:00.001 2019:218:03:29:18.718
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:218:04:45:01.285 2019:219:13:55:44.351
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:218:04:45:01.285 2019:219:13:55:44.351
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:219:14:48:30.146 2019:220:19:30:02.313
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:219:14:48:30.146 2019:220:19:30:02.313
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:221:02:46:02.040 2019:222:12:35:01.285
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:221:02:46:02.040 2019:222:12:35:01.285
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:222:14:05:01.285 2019:223:12:21:08.585
TIMELINES DEBUG: inserting timeline:
	 /2019/AUG0519/oflsa/ 2019:222:14:05:01.285 2019:223:12:21:08.585
```

**Comment by taldcroft** [comment]
Got it, thanks for the explanation.  Going forward we should avoid using touch files so that testing can be done conveniently.

**Comment by jeanconn** [comment]
I think we should avoid them because they are annoying.

**Pull request merged**
